drop table if exists company CASCADE;
drop table if exists employee CASCADE;
create table company (company_id integer generated by default as identity, company_name varchar(255), primary key (company_id));
create table employee (employee_id integer generated by default as identity, age integer not null, company_id integer not null, gender varchar(255), name varchar(255), salary integer not null, employees_company_id integer, primary key (employee_id));
alter table employee add constraint FKjc4fk8mtxj4jnfdtojrfktoor foreign key (employees_company_id) references company;